#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Source files                                                                                                       *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

SOURCES := plm.c
SOURCES += startup-sequential-systick.c

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Product directory                                                                                                  *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

PRODUCT_DIR := product

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#                         Object files directories                                                                     *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

OBJECT_DIR := objects

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Object files                                                                                                       *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

OBJECTS := $(patsubst %, $(OBJECT_DIR)/%.o, $(SOURCES))

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Compiler and linker definition                                                                                     *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

USER_HOME_DIR := $(shell echo ~)

#----------------------------------------------------------------------------------------------------------------------*

TOOL_DIR := $(USER_HOME_DIR)/plm-tools/teensy-i386-Darwin-arm-gcc-4.9.2

#----------------------------------------------------------------------------------------------------------------------*

C_COMPILER_TOOL := $(TOOL_DIR)/bin/arm-eabi-gcc -mthumb -mcpu=cortex-m4

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#    C Compiler options                                                                                                *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

C_COMPILER_OPTIONS := -Wall
C_COMPILER_OPTIONS += -Werror
C_COMPILER_OPTIONS += -Wreturn-type
C_COMPILER_OPTIONS += -Wformat
C_COMPILER_OPTIONS += -Wsign-compare
C_COMPILER_OPTIONS += -Wpointer-arith
C_COMPILER_OPTIONS += -Wparentheses
C_COMPILER_OPTIONS += -Wcast-align
C_COMPILER_OPTIONS += -Wcast-qual
C_COMPILER_OPTIONS += -Wwrite-strings
C_COMPILER_OPTIONS += -Wswitch
C_COMPILER_OPTIONS += -Wuninitialized
C_COMPILER_OPTIONS += -fno-builtin
C_COMPILER_OPTIONS += -Wno-aggressive-loop-optimizations
C_COMPILER_OPTIONS += -ffunction-sections
C_COMPILER_OPTIONS += -fdata-sections
C_COMPILER_OPTIONS += -std=c99
C_COMPILER_OPTIONS += -Wstrict-prototypes
C_COMPILER_OPTIONS += -Wbad-function-cast
C_COMPILER_OPTIONS += -Wmissing-declarations
C_COMPILER_OPTIONS += -Wimplicit-function-declaration
C_COMPILER_OPTIONS += -Wno-int-to-pointer-cast
C_COMPILER_OPTIONS += -Wno-pointer-to-int-cast
C_COMPILER_OPTIONS += -Wmissing-prototypes
C_COMPILER_OPTIONS += -Os
C_COMPILER_OPTIONS += -fomit-frame-pointer
C_COMPILER_OPTIONS += -foptimize-register-move 
C_COMPILER_OPTIONS += -I../build 

#----------------------------------------------------------------------------------------------------------------------*

LINKER_TOOL := $(TOOL_DIR)/bin/arm-eabi-gcc

#----------------------------------------------------------------------------------------------------------------------*

LINKER_OPTIONS := -nostartfiles
LINKER_OPTIONS += -Wl,--fatal-warnings
LINKER_OPTIONS += -Wl,--warn-common
LINKER_OPTIONS += -Wl,--no-undefined
LINKER_OPTIONS += -Wl,--cref
LINKER_OPTIONS += -lc
LINKER_OPTIONS += -lgcc
LINKER_OPTIONS += -Wl,-static
LINKER_OPTIONS += -Wl,-s
LINKER_OPTIONS += -Wl,--gc-sections
LINKER_OPTIONS += -Tsources/linker-script.ld

#----------------------------------------------------------------------------------------------------------------------*

OBJCOPY_TOOL := $(TOOL_DIR)/bin/arm-eabi-objcopy

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Download compiler                                                                                                   *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

$(TOOL_DIR):
	@echo "- Download compiler for teensy"
	$(SILENT_CHAR)python sources/download-compiler.py

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   C Compiler  call                                                                                                   *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

$(OBJECT_DIR)/%.c.o:sources/%.c | $(TOOL_DIR)
	$(SILENT_CHAR)mkdir -p $(OBJECT_DIR)
	@echo "- Compiling: $<"
	$(SILENT_CHAR)$(C_COMPILER_TOOL) -c $< -o $@ $(C_COMPILER_OPTIONS) -MD -MP -MF $(OBJECT_DIR)/$(@F).dep

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Linker call                                                                                                        *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

$(PRODUCT_DIR)/product.elf: $(OBJECTS)
	$(SILENT_CHAR)mkdir -p $(PRODUCT_DIR)
	@echo "- Linking $@"
	$(SILENT_CHAR)$(LINKER_TOOL) $(OBJECTS) $(LINKER_OPTIONS) -Wl,-Map=$@.map -o $@

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   objcopy call                                                                                                       *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

$(PRODUCT_DIR)/product.hex: $(PRODUCT_DIR)/product.elf
	@echo "- Building $@"
	$(SILENT_CHAR)$(OBJCOPY_TOOL) -O ihex $< $@

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   ALL goal                                                                                                           *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

all:$(PRODUCT_DIR)/product.hex

#----------------------------------------------------------------------------------------------------------------------*
#                                                                                                                      *
#   Include dependency files                                                                                           *
#                                                                                                                      *
#----------------------------------------------------------------------------------------------------------------------*

-include $(OBJECT_DIR)/*.dep

#----------------------------------------------------------------------------------------------------------------------*
